# helm upgrade traefik traefik/traefik --namespace=traefik --values=traefik-chart-values.yaml
# https://github.com/traefik/traefik-helm-chart/blob/master/traefik/values.yaml
---
additionalArguments:
  - --entrypoints.websecure.http.tls.certresolver=cloudflare
  - --entrypoints.websecure.http.tls.domains[0].main=example.com
  - --entrypoints.websecure.http.tls.domains[0].sans=*.example.com
  - --certificatesresolvers.cloudflare.acme.dnschallenge.provider=cloudflare
  - --certificatesresolvers.cloudflare.acme.email=mail@example.com
  - --certificatesresolvers.cloudflare.acme.dnschallenge.resolvers=1.1.1.1
  - --certificatesresolvers.cloudflare.acme.storage=/certs/acme.json

#ports:
#  port:
#    web: 80

env:
#  - name: CF_API_EMAIL
#    valueFrom:
#      secretKeyRef:
#        key: email
#        name: cloudflare-api-credentials
#  - name: CF_API_KEY
#    valueFrom:
#      secretKeyRef:
#        key: apiKey
#        name: cloudflare-api-credentials

ingressRoute:
  dashboard:
    enabled: true

persistence:
  enabled: false
  path: /certs
  size: 128Mi